apiVersion: v1
kind: Secret
metadata:
  name: artifactory-credentials
type: Opaque
stringData:
  artifactory_user: user_from_secret
  artifactory_password: 'pass_from_secret!'
  artifactory_host: 'https://from-secret'
  ## artifactory_ca_crt:  optional if artifactory_host is on SSL
  # artifactory_ca_crt: ""
  artifactory_ca_crt: | 
    -----BEGIN CERTIFICATE-----
    ca+_from_secret
    -----END CERTIFICATE-----
