apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: sonarqube-httpproxy
  namespace: sonarqube
spec:
  virtualhost:
    fqdn: sonar-server.h2o-2-22280.h2o.vmware.com ## TODO
    tls:
      secretName: sonar-default-tls
  routes:
    - services:
        - name: sonarqube-sonarqube
          port: 9000

